config/routes.rb
Rails.application.routes.draw do
  post '/d/create', to: 'db#create'
  get '/d/:uid', to: 'db#show', as: 'db'

  resources :db, :path => 'd', :only => [:new]

  get 'stocks.json', to: "db#stocks", as: 'stocks'

  get 'about', to: 'db#about'
  root 'db#index'
end

app/models/db.rb
class Db < ActiveRecord::Base
	serialize :stocks
	serialize :modOrder

	validates :temp, presence: true,
					length: { is: 1 }

	validates :time, presence: true,
					length: { is: 2 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/db_controller.rb
require 'open-uri'
require 'json'

class DbController < ApplicationController
  # create wasn't working without this line
  skip_before_filter :verify_authenticity_token, :only => [:create]

  def new
    # only GET, prefix is new_db
    # Generates a new uid until it is unique and not
    # already in the database. Use the default settings
    # in the database columns for those attributes
    # redirect to the new dashboard via its uid
   	@uid = gen_uid

   	while Db.find_by_uid(@uid) != nil
   		@uid = gen_uid
   	end

   	params[:uid] ||= @uid
   	
   	@db = Db.new(db_params)

   	@db.save
   	redirect_to db_url(@uid)
  end

  def create
    # only POST, prefix is d_create
    # Similar to new however we use the parameters
    # passed in with the POST request to create a new
    # dashboard, then redirect to it with javascript
    # TODO: redirecting via js seems dirty...
    @uid = gen_uid

    while Db.find_by_uid(@uid) != nil
      @uid = gen_uid
    end

    params[:uid] = @uid

    @db = Db.new(create_db_params)
    @db.stocks = params[:stocks]
    @db.modOrder = params[:modOrder]

    @db.save
    render :js => "window.location = '/d/#{@uid}'"
  end

  def about
    # only GET, prefix is about
    # Number of dashboards created shown on the about page
    @count = Db.count
  end

  def show
    # only GET, prefix is db
    # /d/:uid
    # Finds the correct dashboard by uid rather than id
    # then gets the current stock info for the dashboard's stocks
  	@db = Db.find_by_uid(params[:uid])
    @db.stocks = create_stocks(@db.stocks)
  end

  def stocks
    # only GET, prefix is stocks
    # Used for searching for stocks
    # Parsed client-side via jQuery
    q = params[:q]
    results = search_stocks(q)

    render json: results
  end

  private
  	def db_params
      # Used for new
  		params.permit(:uid)
  	end

    def create_db_params
      # Used for create
      params.permit(:uid, :time, :temp, :stocks, :modOrder, :loc, :bg, :fg)
    end
end

def gen_uid
  # Generates a pseudo-random 10 character string to be used as a dashboard's uid
  # 107,518,933,731 unique combinations
	o = [('a'..'z'), ('A'..'Z'), (0..9)].map { |i| i.to_a }.flatten
	string = (0..10).map { o[rand(o.length)] }.join

	return string
end

def get_stock_info(symbol)
  # Gets the current stock information based on the symbol given
  # also checks to see if it was sucessful in getting the stock info
  url = 'http://dev.markitondemand.com/Api/v2/Quote/json?symbol=' + symbol
  content = open(url).read
  data = JSON.parse(content)

  my_data = Hash.new
  my_data['success'] = data['Status'] == 'SUCCESS'

  if my_data['success']
    my_data['price'] = '%.2f' % data['LastPrice']
    my_data['percent'] = data['ChangePercent'].round(2)
  end

  my_data['name'] = symbol.upcase
  return my_data
end

def create_stocks(stocks)
  # Goes through all the stocks in the stocks array
  # a while loop was needed over stocks.each because
  # we are saving the data back to the stocks array
  i = 0
  while (i < stocks.length)
    stocks[i] = get_stock_info(stocks[i])
    i += 1
  end

  return stocks
end

def search_stocks(q)
  # Used for stocks, searches for stocks based on a query
  # returns the raw data to be used in stocks then parsed
  # client-side via jQuery
  search_url = 'http://dev.markitondemand.com/Api/v2/Lookup/json?input=' + q
  search_content = open(search_url).read

  return search_content
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/db_helper.rb
module DbHelper
end

app/views/db/_clock.html.erb
<div class="portlet">
	<div class="row portlet-content mod" id="clock">
	  <h1><span id="time"></span></h1>
	</div>
</div>

app/views/db/_color_modal.html.erb
<div class="modal fade" id="color_pick">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" onclick="resetColor()" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Change Dashboard Colors</h4>
      </div>
      <div class="modal-body">
        <h2>Background Color</h2>
        <div class="input-group colorpicker-component demo demo-auto color" id="color_bg">
            <input type="text" value="<%= @db.bg %>" class="form-control" id="bg" />
            <span class="input-group-addon"><i></i></span>
        </div>
        <h2>Foreground (text) Color</h2>
        <div class="input-group colorpicker-component demo demo-auto color" id="color_fg">
            <input type="text" value="<%= @db.fg %>" class="form-control" id="fg" />
            <span class="input-group-addon"><i></i></span>
        </div>
      </div>
      <div class="modal-footer">
         <button type="button" class="btn btn-danger" onclick="resetColor()" data-dismiss="modal"><i class="fa fa-fw fa-warning"></i> Discard changes</button>
          <button type="button" class="btn btn-success" onclick="saveColor()" data-dismiss="modal"><i class="fa fa-fw fa-check"></i> Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/db/_copy_modal.html.erb
<div class="modal fade" id="copy_link">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Copy Link</h4>
      </div>
      <div class="modal-body">
        <h2 class="text-center"><span id='modal_url'><%= link_to "Copy Me", db_path(@db.uid) %></span></h2>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-primary" data-dismiss="modal">Done</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/db/_date.html.erb
<div class="portlet">
	<div class="row portlet-content mod" id="date">
	  <h3><span id="month"></span> <span id="day"></span>, <span id="year"></span></h3>
	</div>
</div>

app/views/db/_menu.html.erb
<div class="menu-wrap">
  <nav class="menu">
    <div class="profile"><span id="title"><span id='menu_url'><%= @db.uid %></span> <a onclick="copy()"><i class="fa fa-fw fa-link"></i></a></span></div>
    <div class="link-list">
      <p><a onclick="getWWL('c', true)">&deg;C</a> / <a onclick="getWWL('f', true)">&deg;F</a></p>
      <p><a onclick="updateClock('24');sendData(data)">24h</a> / <a onclick="updateClock('12');sendData(data)">12h</a></p>
      <p><a onclick="changeStocks()">Stocks <i class="fa fa-fw fa-bar-chart"></i></a></p>
      <p><a onclick="changeWeather()">Location <i class="fa fa-fw fa-cloud"></i></a></p>
      <p><a onclick="changeColor()">Colors <i class="fa fa-fw fa-eyedropper"></i></a></p>
    </div>
    <div class="icon-list">
      <a href="/about/"><i class="fa fa-fw fa-question-circle"></i></a>
      <a onclick="edit()" id="edit"><i class="fa fa-fw fa-pencil"></i></a>
      <a onclick="save()" id="save"><i class="fa fa-fw fa-save"></i></a>
    </div>
  </nav>
</div>
<button class="menu-button" id="open-button"><i class="fa fa-fw fa-cog"></i><span>Open Menu</span></button>

app/views/db/_news.html.erb
<div class="portlet">
<div class="row text-left portlet-content mod" id="news">
</div>
</div>

app/views/db/_stocks.html.erb
<div class="portlet">
  <div class="row text-center portlet-content mod" id="stocks">
    <% @db.stocks.each do |stock| %>
      <% if stock['success'] %>
        <div class="col-xs-3">
          <h4 class="title"><%= stock['name'] %></h4>
          <p class="price">$<%= stock['price'] %></p>
          <p class="percent"><i class="fa fa-fw <% if stock['percent'] > 0 %>fa-arrow-up green<% elsif stock['percent'] < 0 %>fa-arrow-down red<% else %>fa-ellipsis-h<% end %>"></i><br class="rwd-break" /><%= stock['percent'].abs %>%</p>
        </div>
      <% else %>
        <div class="col-xs-3">
          <h4 class="title">Stock: <%= stock['name'] %> not found!</h4>
        </div>
      <% end %>
    <% end %>
  </div>
</div>

app/views/db/_weather.html.erb
<div class="portlet">
  <div class="row portlet-content mod" id="weather">
    <div id="g_weather">
      <div class="col-md-4" id="today">
          <h4>Today</h4><br>
          <div class="row">
            <div class="col-xs-6 text-right">
              <p class="icon"></p>
            </div>
            <div class="col-xs-6 text-left">
              <p><span class="cond"></span></p>
              <p><i class="fa fa-arrow-up fa-fw"></i> <span class="high">0</span>&deg; &nbsp; <br class="rwd-break" /><i class="fa fa-arrow-down fa-fw"></i> <span class="low">0</span>&deg;</p>
            </div>
          </div>
      </div>

      <div class="col-md-4" id="tmw">
          <h4>Tomorrow</h4><br>
          <div class="row">
            <div class="col-xs-6 text-right">
              <p class="icon"></p>
            </div>
            <div class="col-xs-6 text-left">
              <p><span class="cond"></span></p>
              <p><i class="fa fa-arrow-up fa-fw"></i> <span class="high">0</span>&deg; &nbsp; <br class="rwd-break" /><i class="fa fa-arrow-down fa-fw"></i> <span class="low">0</span>&deg;</p>
            </div>
          </div>
      </div>

      <div class="col-md-4" id="dat">
          <h4><span id="dat_name"></span></h4><br>
          <div class="row">
            <div class="col-xs-6 text-right">
              <p class="icon"></p>
            </div>
            <div class="col-xs-6 text-left">
              <p><span class="cond"></span></p>
              <p><i class="fa fa-arrow-up fa-fw"></i> <span class="high">0</span>&deg; &nbsp; <br class="rwd-break" /><i class="fa fa-arrow-down fa-fw"></i> <span class="low">0</span>&deg;</p>
            </div>
          </div>
      </div>
    </div> <!-- end g_weather -->

    <div id="b_weather">
      <h2>Error with given location. <a onclick="changeWeather()">Click here to change it.</a></h2>
    </div>
  </div>
</div> <!-- end portlet -->

app/views/db/_weather_modal.html.erb
<div class="modal fade" id="weather_modal">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title">Weather Location</h4>
      </div>
      <div class="modal-body">
        <p>You may change your weather location or leave it on auto where it will get the weather based on your location.</p>
        <div class="sb text-center">
            <p>Enter location</p>
            <input type="edit" placeholder="Enter new location" id="w_sb">
            <p id="error">Please enter a valid location</p>
            <p><em>or</em> <a onclick="editWeather(true)">set to auto</a></p>
            <br><h4>Current: <em><%= @db.loc %></em></h4>
        </div><br>
      </div>
      <div class="modal-footer">
         <button type="button" class="btn btn-danger" data-dismiss="modal"><i class="fa fa-fw fa-warning"></i> Discard changes</button>
          <button type="button" class="btn btn-success" onclick="editWeather(false)"><i class="fa fa-fw fa-check"></i> Save changes</button>
      </div>
    </div><!-- /.modal-content -->
  </div><!-- /.modal-dialog -->
</div><!-- /.modal -->

app/views/db/about.html.erb
<% content_for :title do %>About Us - <% end %>

<div class="container">

  <div class="text-center" id="content">
  	<h1>About</h1>
  	<h3 class="text-left">Background</h3>
  	<p class="text-left">The Open Dashboard project was started in 2014 by <%= link_to "ZUMH", "http://zumh.org" %>. It was originally intended to be a quick and easy way to see the date &amp; time. From that it has grown to include the weather, news &amp; stocks; as well as allowing much more customization than the original. The main emphasis is that this project is completely open source to everyone! You can find us on <i class='fa fa-fw fa-github'></i><%= link_to "GitHub", "https://github.com/tizz98/opendash" %> and look below to see the number of dashboards created with this website!</p><br>
  	<p>Number of dashboards created</p>
  	<h2><%= @count %></h2>

  	<div class="row" id="links">
  	  	<div class="col-xs-4">
  			<h2><i class="fa fa-fw fa-home"></i><%= link_to "Home", root_path %></h2>
  		</div>
  		<div class="col-xs-4">
  			<h2><i class="fa fa-fw fa-rocket"></i><%= link_to "ZUMH", "http://zumh.org" %></h2>
  		</div>
  		<div class="col-xs-4">
  			<h2><i class="fa fa-fw fa-github"></i><%= link_to "GitHub", "https://github.com/tizz98/opendash" %></h2>
  		</div>
  	</div>

    <div class="howto">
        <h1>How-To's</h1>
        <hr>
        <h3>Moving sections</h3>
        <img src="http://i.gyazo.com/e0215bc4b25d9fea70c5e2e0401fc847.gif" class="img-responsive"/>
        <p>As you see above, you click the settings icon in the lower left hand corner then the pencil icon to allow you to move the sections. After you click and drag the sections to where you want, click the save icon in the pop up panel.</p>
        <img src="http://i.gyazo.com/d33b27f921399b155acbb6a82cd66f13.gif" class="img-responsive"/>
        <p>You will then be redirected to your newly saved page!</p>
        <hr>
        <h3>Moving &amp; Searching for stocks</h3>
        <img src="http://i.gyazo.com/1c595bf695242e8eee3e6d1721937d3a.gif" class="img-responsive">
        <p>After clicking the stocks link in the menu popup you can click and drag the stocks around to where you'd like. You can also search for a stock in the search box.</p>
        <img src="http://i.gyazo.com/84321295bf8edaf146f4c9c406eae367.gif" class="img-responsive">
        <p>After you've found a stock you like, click the pencil icon next to one you don't want anymore and type in the new one. Hit the save icon next to it, then the <em>Save Changes</em> button. You will be redirected to your new page with your stocks as shown below.</p>
        <img src="http://i.gyazo.com/7bfaa8cd7795755215aefeaa872e9512.png" class="img-responsive"/>
        <hr>
        <h3>Time &amp; Temperature</h3>
        <img src="http://i.gyazo.com/a69f8fa2ca696a23cd00961a45beaf8c.png" class="img-responsive"/>
        <p>If you want to change the time to 24 hour or 12 hour time, just click which one you want and it'll be saved and you'll be redirected to your new page. Same with temperature, change it to Celsius or Fahrenheit.</p>
        <hr>
        <h3>Miscellaneous</h3>
        <p>Everytime you save a change to the page you will be redirected to one with your personalized settings. Be sure to update your bookmark for the newly generated link!</p>
    </div>
  </div>
</div>

app/views/db/create.html.erb
<h1>Create</h1>

app/views/db/index.html.erb
<% content_for :css do %><%= stylesheet_link_tag "home" %><% end %>

<div class="wrap"> <a href="/d/default/">
    <div class="fleft">
         <h1>Create New Dashboard</h1>

        </div></a>
 <a href="/about/">
    <div class="fright">
         <h1>About Us</h1>

        </div></a>

</div>

app/views/db/new.html.erb
<h1>new</h1>
<%= @db.temp %>
<%= @db.time %>
<% @db.stocks.each do |stock| %>
	<%= stock %>
<% end %>
<% @db.modOrder.each do |mod| %>
	<%= mod %>
<% end %>
<%= @db.uid %>

app/views/db/show.html.erb
<% content_for :title do %>My Dashboard - <% end %>
<% content_for :css do %><style type="text/css">
	body, .container {
		background-color: <%= @db.bg %>;
		color: <%= @db.fg %>;
	}
</style><% end %>

<%= render 'db/menu' %>

<div class="container">

  <div class="text-center" id="content">

    <div class="column">
    	<% @db.modOrder.each do |mod| %>
			<% if mod == 'date' %>
				<%= render 'db/date' %>
			<% elsif mod == 'clock' %>
				<%= render 'db/clock' %>
			<% elsif mod == 'news' %>
				<%= render 'db/news' %>
			<% elsif mod == 'stocks' %>
				<%= render 'db/stocks' %>
			<% elsif mod == 'news' %>
				<%= render 'db/news' %>
			<% elsif mod == 'weather' %>
				<%= render 'db/weather' %>
			<% end %>
		<% end %>
    </div>

  </div>
</div>

<%= render 'db/copy_modal' %>
<%= render 'db/stocks_modal' %>
<%= render 'db/weather_modal' %>
<%= render 'db/color_modal' %>

<script type="text/javascript">
	data = {
		temp: '<%= @db.temp %>',
		time: '<%= @db.time %>',
		stocks: [<% @db.stocks.each do |stock| %>'<%= stock['name'] %>'<% if stock != @db.stocks.last %>,<% end %><% end %>],
		modOrder: [<% @db.modOrder.each do |mod| %>'<%= mod %>'<% if mod != @db.modOrder.last %>,<% end %><% end %>],
		loc: '<%= @db.loc %>',
		bg: '<%= @db.bg %>',
		fg: '<%= @db.fg %>',
	}
</script>

<%= content_for :js do %>
<%= javascript_include_tag "dash.min" %>
<script type="text/javascript">
	getWWL('<%= @db.temp %>', false, '<%= @db.loc %>', true);
	updateClock('<%= @db.time %>');
</script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <title><%= yield :title %>The Open Dashboard Project</title>
  <%= favicon_link_tag 'icon.ico' %>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="An open source personal dashboard.">
	<meta name="keywords" content="dashboard, personal dashboard, ruby, rails, zumh, open source, open source projects, elijah wilson, elijah">
	<meta name="robot" content="index,follow">
	<meta name="author" content="Elijah Wilson">
	<meta name="language" content="English">
	<meta name="revisit-after" content="30">
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" %>
  <%= stylesheet_link_tag "https://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" %>
  <%= stylesheet_link_tag "http://fonts.googleapis.com/css?family=Lato&subset=latin,latin-ext" %>
  <%= stylesheet_link_tag "normalize.css", "menu.css", "style.css", "weather-icons.min.css", "portlets.css", "stocks.css", 'bootstrap-colorpicker.css'%>
  <%= yield :css %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= javascript_include_tag 'https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js',
'https://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js', 'tracking.min' %>
<%= yield :js %>
</body>
</html>